INSERT INTO condition_catalog (id, code, display_name, display_name_es, description, description_es, display_order, active, created_at, updated_at) VALUES (RANDOM_UUID(), 'CHLAMYDIA', 'Chlamydia', 'Clamidia', 'Chlamydia trachomatis', 'Chlamydia trachomatis', 1, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO condition_catalog (id, code, display_name, display_name_es, description, description_es, display_order, active, created_at, updated_at) VALUES (RANDOM_UUID(), 'GONORRHEA', 'Gonorrhea', 'Gonorrea', 'Neisseria gonorrhoeae', 'Neisseria gonorrhoeae', 2, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO condition_catalog (id, code, display_name, display_name_es, description, description_es, display_order, active, created_at, updated_at) VALUES (RANDOM_UUID(), 'SYPHILIS', 'Syphilis', 'Sifilis', 'Treponema pallidum', 'Treponema pallidum', 3, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO condition_catalog (id, code, display_name, display_name_es, description, description_es, display_order, active, created_at, updated_at) VALUES (RANDOM_UUID(), 'HIV', 'HIV', 'VIH', 'Human Immunodeficiency Virus', 'Virus de Inmunodeficiencia Humana', 4, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO condition_catalog (id, code, display_name, display_name_es, description, description_es, display_order, active, created_at, updated_at) VALUES (RANDOM_UUID(), 'HSV1', 'HSV-1', 'VHS-1', 'Herpes Simplex Virus Type 1', 'Virus del Herpes Simple Tipo 1', 5, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO condition_catalog (id, code, display_name, display_name_es, description, description_es, display_order, active, created_at, updated_at) VALUES (RANDOM_UUID(), 'HSV2', 'HSV-2', 'VHS-2', 'Herpes Simplex Virus Type 2', 'Virus del Herpes Simple Tipo 2', 6, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO condition_catalog (id, code, display_name, display_name_es, description, description_es, display_order, active, created_at, updated_at) VALUES (RANDOM_UUID(), 'HPV', 'HPV', 'VPH', 'Human Papillomavirus', 'Virus del Papiloma Humano', 7, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO condition_catalog (id, code, display_name, display_name_es, description, description_es, display_order, active, created_at, updated_at) VALUES (RANDOM_UUID(), 'HEPATITIS_B', 'Hepatitis B', 'Hepatitis B', 'Hepatitis B Virus', 'Virus de la Hepatitis B', 8, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO condition_catalog (id, code, display_name, display_name_es, description, description_es, display_order, active, created_at, updated_at) VALUES (RANDOM_UUID(), 'HEPATITIS_C', 'Hepatitis C', 'Hepatitis C', 'Hepatitis C Virus', 'Virus de la Hepatitis C', 9, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO condition_catalog (id, code, display_name, display_name_es, description, description_es, display_order, active, created_at, updated_at) VALUES (RANDOM_UUID(), 'TRICHOMONIASIS', 'Trichomoniasis', 'Tricomoniasis', 'Trichomonas vaginalis', 'Trichomonas vaginalis', 10, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO network_stages (id, code, display_name, display_name_es, min_nodes, max_nodes, description, description_es, display_order, created_at) VALUES (RANDOM_UUID(), 'EMPTY_SKY', 'Empty Sky', 'Cielo Vacío', 0, 0, 'No connections yet', 'Sin conexiones aún', 0, CURRENT_TIMESTAMP);
INSERT INTO network_stages (id, code, display_name, display_name_es, min_nodes, max_nodes, description, description_es, display_order, created_at) VALUES (RANDOM_UUID(), 'BINARY_STAR', 'Binary Star', 'Estrella Binaria', 1, 2, 'First connections', 'Primeras conexiones', 1, CURRENT_TIMESTAMP);
INSERT INTO network_stages (id, code, display_name, display_name_es, min_nodes, max_nodes, description, description_es, display_order, created_at) VALUES (RANDOM_UUID(), 'CONSTELLATION', 'Constellation', 'Constelación', 3, 10, 'Growing network', 'Red en crecimiento', 2, CURRENT_TIMESTAMP);
INSERT INTO network_stages (id, code, display_name, display_name_es, min_nodes, max_nodes, description, description_es, display_order, created_at) VALUES (RANDOM_UUID(), 'GALAXY', 'Galaxy', 'Galaxia', 11, NULL, 'Large network', 'Red amplia', 3, CURRENT_TIMESTAMP);
